# Generated by Django 2.2.8 on 2019-12-16 22:56

import django.core.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(default='usuarios/avatar.png', upload_to='usuarios/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(message="El formato del teléfono debe ser: '9998888777', sin código de país. De 8-14 dígitos permitidos. Puede agregar más telefonos seperados por coma.", regex='^\\d{8,14}((,\\d{8,14})?)*$')], verbose_name='Teléfono Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
