# Generated by Django 2.2.8 on 2021-03-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('symbol', models.CharField(max_length=5, verbose_name='Simbolo')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('product_type', models.CharField(choices=[('Experiencia', 'experience'), ('Tour', 'tour'), ('Ticket', 'ticket'), ('Extras', 'extra'), ('Descuento', 'discount')], max_length=50, verbose_name='Tipo de producto')),
                ('product_id', models.IntegerField(verbose_name='ID del producto')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='', max_length=150, verbose_name='Tipo de movimiento')),
                ('concept', models.CharField(blank=True, max_length=300, null=True, verbose_name='Concepto')),
                ('reference', models.CharField(max_length=300, verbose_name='Referencia')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto de transaccion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costcenter.Product')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='ExchangeCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor de la moneda')),
                ('rota_equivalence', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Equivalencia Rotapuntos')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costcenter.Coin')),
            ],
            options={
                'verbose_name': 'Centro de Cambio',
                'verbose_name_plural': 'Centros de cambio',
            },
        ),
    ]
